name: 获取热门新闻

on:
  workflow_dispatch:
  push:  # 只要你修改文件，它就会自动跑一次

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装环境
        run: pip install -r requirements.txt
      - name: 执行抓取
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
